language: python3
before_install:
  - echo "BEFORE INSTALL START"
  - gem install bundler
  - echo "BEFORE INSTALL END"
script:
  pip3 install pygame
  pip3 install pynput
  python3 game.py
branches:
  only:
  - gh-pages
  - /.*/
